project:
  type: website
  output-dir: docs

website:
  title: "Hinano Kamenosono"
  navbar:
    left:
      - href: index.qmd
        text: Home
  page-footer: Hinano Kamenosono 2024
  google-analytics: "G-DSGZRHN260"

format:
  html:
    mainfont: Noto Sans JP, Helvetica Neue, Arial, "Hiragino Kaku Gothic ProN" "Hiragino Sans", "BIZ UDPGothic", Meiryo, sans-serif
    # fontsize: 20pt
    theme: minty
    toc: true
    toc-title: " "
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="Skv6aQeeeA2hxyd_3Xgn7CIFl6LQgj6LkOCVwygGtKo" />
      - file: analytics.html
      - comments.html
    include-before-body: header.html

lang: ja
