---
title: "Hinano Kamenosono / 亀之園 ひなの"
about:
  template: solana
  id: heading
  links: 
    - text: Mail
      icon: envelope
      href: mailto:khina@shs.ens.titech.ac.jp
---

:::{#heading}

::: {.panel-tabset}
# English

## Education
Tokyo Institute of Technology, M2 (Apr.2023-present)

Tsuda University, B.A. in Policy Studies (Apr.2019-Mar.2023)

## Job Experiments
Teaching Assistant "International Relations A" in Tokyo Institute of Technology (Oct.2024-Nov.2024)<br>
Teaching Assistant "International Relations C" in Tokyo Institute of Technology (Apr.2024-Jun.2024)<br>
Teaching Assistant "Data Science" (Required) in the Department of Policy Studies, Tsuda University (Apr.2024-Jun.2024)<br>
Teaching Assistant "Statistics A" (Required) in the Department of Policy Studies, Tsuda University (Sep.2024-Nov.2024)<br>
Teaching Assistant "Statistics B" (Required) in the Department of Policy Studies, Tsuda University (Nov.2024-Jan.2025)<br>
Teaching Assistant "Statistics B" (Required) in the Department of Policy Studies, Tsuda University (Nov.2023-Jan.2024)

## Association
[Base Politics](https://www.basepoliticsjp.com/){target="_blank"}

## Research Theme
Survey Experiments<br>
Local Public Opinion<br>
US military bases in Okinawa

## Experience
Master's Thesis: "A Okinawa-National Comparative Experimental Study with a Hypothetical Taiwan Contingency: The Effects of Signaling and Backing Down" (M.A. Expected: March 2025)

Graduation Thesis: "Analysis of the National Security Schemes through Energy Trade: Comparison between Japan and Taiwan" (2023)

[1]	Tago, A. and Kamenosono, H. “Status Perception under the Crisis: A Comparison of National and Okinawa Samples.” Pacific International Politics Conference (2024 PIPC). Jul. 2024. (Oral, Reviewed)<br>
[2]	Kamenosono, H. “Assurance and Threats in a Taiwan Contingency Scenario: Public Opinion in Japan and Okinawa.” JSQPS. Kochi University of Technology, Jul. 2024. (Oral, Reviewed)<br>
[3]	Kamenosono, H. “Public Opinion Comparison between Okinawa and National with Taiwan Crisis Scenario.” JSPS Kakenhi (Grant-in-Aid for Scientific Research, Pioneering) Workshop: "Exploring Strategies for Pioneering Research and Political Science Analysis Using Innovative Methods by Early-Career Researchers" Waseda University. Mar. 2024. (Oral)<br>
[4]	Kamenosono, H. "Public Opinion on U.S. Military Bases in Okinawa"　Waseda University, WE-SPICE （26, Sept. 2023）　[WE-SIPCE 2023](https://www.waseda.jp/inst/sgu/news/2023/09/26/26911/){target="_blank"} （Poster Presentation）<br>

Kamenosono, H. and Tago, A. "Public Opinion Study on US Military Bases: A Survey Experiment with Taiwan Crisis" (Jan. 2024) OSF Registries <https://doi.org/10.17605/OSF.IO/SPU4R>

## Maps
::: {.grid}

::: {.grid-auto-fit}
:::{.callout-note}
## [Shinji Kawana Lab](https://sites.google.com/view/kawanalab){target="_blank"} @Tokyo Tech

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1621.9433944506384!2d139.6824459!3d35.6058591!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018f5c7cc7bd92d%3A0xc8499216b1e3dd28!2z5p2x5Lqs5bel5qWt5aSn5a2mIOilvznlj7fppKg!5e0!3m2!1sja!2sjp!4v1695984121571!5m2!1sja!2sjp" width="auto" height="auto" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
:::

:::

::: {.grid-auto-fit}
:::{.callout-note}
## [Atsushi Tago Lab](https://a-tago.github.io/){target="_blank"} @Waseda

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d924.9990165076774!2d139.7190011967158!3d35.708478600163374!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188d1b65b68f05%3A0x548ad5986c6f7ee1!2z44CSMTY5LTAwNTEg5p2x5Lqs6YO95paw5a6_5Yy66KW_5pep56iy55Sw77yR5LiB55uu77yW4oiS77yRIOaXqeeosueUsOWkp-WtpiAz5Y-36aSo!5e0!3m2!1sja!2sjp!4v1695984163272!5m2!1sja!2sjp" width="auto" height="auto" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
:::

:::

:::

# 日本語

## 学歴
東京工業大学　環境・社会理工学院　社会・人間科学系　修士課程2年　（2023年4月〜現在）

津田塾大学　総合政策学部　総合政策学科　（2019年4月〜2023年3月）

## 職歴
東京工業大学　文系教養科目TA（「国際関係論A」）（2024年10月〜2024年11月）<br>
東京工業大学　文系教養科目TA（「国際関係論C」）（2024年4月〜2024年6月）<br>
津田塾大学　総合政策学部　総合政策学科TA（「データ・サイエンス入門」必修科目）（2024年4月〜2024年6月）<br>
津田塾大学　総合政策学部　総合政策学科TA（「統計A」必修科目）（2024年9月〜2024年11月）<br>
津田塾大学　総合政策学部　総合政策学科TA（「統計B」必修科目）（2024年11月〜2025年1月）<br>
津田塾大学　総合政策学部　総合政策学科TA（「統計B」必修科目）（2023年11月〜2024年1月）

## 所属研究会
[基地政治研究会](https://www.basepoliticsjp.com/){target="_blank"}

## 研究テーマ
サーベイ実験<br>
ローカル世論<br>
沖縄の米軍基地

## 業績
修士論文：「仮想・台湾有事における日本政府の対応をめぐる沖縄県民と他県民の支持態度比較実験：シグナルとバックダウンの影響」2025年3月修士取得見込み<br>
学士論文：「資源エネルギー貿易に着目した日本と台湾の安全保障体制の比較考察」2023年3月学士取得

**サーベイ実験**<br>
Kamenosono, H. and Tago, A. "Public Opinion Study on US Military Bases: A Survey Experiment with Taiwan Crisis" (Jan. 2024) OSF Registries <https://doi.org/10.17605/OSF.IO/SPU4R>

**口頭発表**<br>
国際会議での発表<br>
[1]	Tago, A. and Kamenosono, H. “Status Perception under the Crisis: A Comparison of National and Okinawa Samples.” Pacific International Politics Conference (2024 PIPC). 2024年7月. （口頭・査読あり）

学会・ワークショップでの発表<br>
[1]	Kamenosono, H. “Assurance and Threats in a Taiwan Contingency Scenario: Public Opinion in Japan and Okinawa.” 計量・数理政治学会（JSQPS）. 高知工科大学, 高知県, 2024年7月. （口頭・査読あり）<br>
[2]	Kamenosono, H. “Public Opinion Comparison between Okinawa and National with Taiwan Crisis Scenario.” 科学研究費・開拓研究ワークショップ「若手研究者による新しい手法による政治学分析と開拓研究の戦略の検討」早稲田大学, 東京都, 2024年3月. （口頭・査読なし）<br>
[3]	Kamenosono, H. "Public Opinion on U.S. Military Bases in Okinawa"　早稲田大学WE-SPICE （2023年9月26日）　[WE-SIPCE 2023](https://www.waseda.jp/inst/sgu/news/2023/09/26/26911/){target="_blank"} （ポスター発表・査読なし）<br>

その他<br>
「法人税率の差異は国際資本移動の要因となるか？―マクロ統計からのBEPS考察―」インターゼミナール2021年12月19日<br>
「資源エネルギー貿易に着目した日本と台湾の安全保障体制の比較考察」インターゼミナール2022年12月11日<br>
「資源エネルギー貿易に着目した海上輸送の安全保障」税関発足150周年事業『大学生フォーラム』2023年3月7日

## Maps
::: {.grid}

::: {.grid-auto-fit}
:::{.callout-note}
## [川名 晋史 研究室](https://sites.google.com/view/kawanalab){target="_blank"} @Tokyo Tech

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1621.9433944506384!2d139.6824459!3d35.6058591!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018f5c7cc7bd92d%3A0xc8499216b1e3dd28!2z5p2x5Lqs5bel5qWt5aSn5a2mIOilvznlj7fppKg!5e0!3m2!1sja!2sjp!4v1695984121571!5m2!1sja!2sjp" width="auto" height="auto" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
:::

:::

::: {.grid-auto-fit}
:::{.callout-note}
## [多湖 淳 研究室](https://a-tago.github.io/){target="_blank"} @Waseda

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d924.9990165076774!2d139.7190011967158!3d35.708478600163374!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188d1b65b68f05%3A0x548ad5986c6f7ee1!2z44CSMTY5LTAwNTEg5p2x5Lqs6YO95paw5a6_5Yy66KW_5pep56iy55Sw77yR5LiB55uu77yW4oiS77yRIOaXqeeosueUsOWkp-WtpiAz5Y-36aSo!5e0!3m2!1sja!2sjp!4v1695984163272!5m2!1sja!2sjp" width="auto" height="auto" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
:::

:::

:::

:::

:::